# Generated by Django 4.1 on 2022-10-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_address',
        ),
    ]
