# Generated by Django 4.1 on 2022-10-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_remove_post_user_address'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_address',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
