# Generated by Django 4.1 on 2022-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0005_alter_commentnotification_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnotification',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='welcomenotification',
            name='msg',
            field=models.TextField(),
        ),
    ]
