# Generated by Django 4.1 on 2022-11-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_remove_post_user_address'),
        ('Notification', '0006_alter_commentnotification_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnotification',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Posts.comments'),
        ),
    ]
